### ISSUE TITLE
Arkose challenges

### ISSUE THREAD

**Issue by iCankat** [Twitter-Tools/TwitterAccountGenerator#1]
Hello, the script is working fantastically. However, I'm facing an issue that I'm not sure how to handle. After some accounts are opened, they receive a warning named "Arkose." Is there a chance you could add an extra piece of code to solve this? It seems the problem can be overcome by logging into the account with a token and solving a captcha, but I couldn't manage to do it. I think it might be a problem that you could solve in just a few minutes. I hope you can add this feature as well. Thanks for everything.

**Comment by Twitter-Tools** [comment]
You can use [my other open source tool](https://github.com/Twitter-Tools/TwitterTokensUnlocker) to do this automatically

**Comment by iCankat** [comment]
It escaped my notice. Thanks.
