### ISSUE TITLE
invalid ELF header

### ISSUE THREAD

**Issue by phinwww** [Twitter-Tools/TwitterAccountGenerator#2]
hi, 
i get this whenever I run the program.
what am i doing wrong?

Traceback (most recent call last):
  File "/root/TwitterAccountGenerator/main.py", line 12, in <module>
    import helpers
  File "/root/TwitterAccountGenerator/helpers/__init__.py", line 9, in <module>
    from . import twitter
  File "/root/TwitterAccountGenerator/helpers/twitter.py", line 14, in <module>
    LIBRARY = ctypes.CDLL("helpers/instrumentation.so")
  File "/usr/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: helpers/instrumentation.so: invalid ELF header

**Comment by phinwww** [comment]
for context:
i downloaded all the requirements in the requirements.txt file

**Comment by phinwww** [comment]
Nevermind, I see the problem. 
instrumentation.so is for Windows.
I was running this on a linux machine.

**Comment by phinwww** [comment]
still hangs on my windows vm and doesnt do anything. im probably just retarded though

**Comment by Twitter-Tools** [comment]
indeed being on linux was the issue, if it's still not working for you, you can try changing [this line](https://github.com/Twitter-Tools/TwitterAccountGenerator/blob/main/helpers/__init__.py#L36) to
```py
logger.setLevel(logging.DEBUG)
```
to see what's going on

**Comment by phinwww** [comment]
ok, lemme try

**Comment by phinwww** [comment]
nothing logged after i run it, it just hangs. weird. ill try on another VM or real machine

**Comment by phinwww** [comment]
is there a linux equivalent to the `instrumentation.so` file?

**Comment by ahmetbbt** [comment]
@Twitter-Tools 
instrumentation.so is a DLL file which doesn't work with Mac or Linux machines. Is there instrumentation file for unix based operating systems?

**Comment by Twitter-Tools** [comment]
> is there a linux equivalent to the `instrumentation.so` file?

there is not

**Comment by ahmetbbt** [comment]
@Twitter-Tools if you tell me (where to get / how to create) this instrumentation, I can generate a file which runs properly in unix-based machines.

**Comment by Twitter-Tools** [comment]
> @Twitter-Tools if you tell me (where to get / how to create) this instrumentation, I can generate a file which runs properly in unix-based machines.

instrumentation.so is used to solve twitter's antibot challenge, you need to reverse the challenge, you can find it [here](https://twitter.com/i/js_inst?c_name=ui_metrics)

**Comment by Twitter-Tools** [comment]
> nothing logged after i run it, it just hangs. weird. ill try on another VM or real machine

change [this line](https://github.com/Twitter-Tools/TwitterAccountGenerator/blob/main/main.py#L960) and the one below to look like this:
```python
except Exception as e:
    print(f'An error happened: {e}')
```

**Comment by phinwww** [comment]
> > nothing logged after i run it, it just hangs. weird. ill try on another VM or real machine
> 
> change [this line](https://github.com/Twitter-Tools/TwitterAccountGenerator/blob/main/main.py#L960) and the one below to look like this:
> 
> ```python
> except Exception as e:
>     print(f'An error happened: {e}')
> ```

**502 Gateway Error**

ok so its a serverside problem (or something with my DNS), weird
