### ISSUE TITLE
Can't complete your signup right now

### ISSUE THREAD

**Issue by ahmetbbt** [Twitter-Tools/TwitterAccountGenerator#7]
All my attempts today got this error:
"Can't complete your signup right now"

I tried different proxies. yet the result did not change.

However, 60% of my attempts yesterday were successful. 

Do you have any idea what happened today?

**Comment by ahmetbbt** [comment]
I think this is a temporary situation, as stated in the message.

It may even vary depending on the server load on Twitter.

**Comment by Twitter-Tools** [comment]
I have already answered this question so many times

**Comment by Spikesdev** [comment]
I get Can't complete your signup right now. on sign in page aswell even tho there is no needed captcha. What is causing Can't complete your signup right now.?
